update swiss army and lrgs maintainer sentance
opendcs/opendcs pull request #541
Opened 2024-03-29 21:11 UTC by zamusacelre

add swiss army knife and sentence in lrgs doc

## Problem Description

Fixes #. 

Describe the problem you are trying to solve.

## Solution

Describe your solution.

## how you tested the change

Describe what was done to test the change. This section can be left blank 
if automated tests demonstrating usage are provided in the PR.

## Where the following done:

- [ ] Tests. Check all that apply:
   - [ ] Unit tests created or modified that run during ant test.
   - [ ] Integration tests created or modified that run during integration testing
         (Formerly called regression tests.)
   - [ ] Test procedure descriptions for manual testing
- [ ] Was relevant documentation updated?
- [ ] Were relevant config element (e.g. XML data) updated as appropriate

If you aren't sure leave unchecked and we will help guide you to want needs changing where.

2024-03-29 22:14 UTC, ktarbet commented on docs/source/media/start/software/im-00-swiss-army-knife.JPG
consider:  consistent use of periods or not ending with periods.

consider changing:   I want to calculate some hydrologic specific information based on time series in database
to:
I want to calculate some hydrologic specific information based on time series data.

consider chaining: I want to retrieve data from web and store in database
to:
 I want to retrieve data from *the* web and store in *a* database

2024-03-29 22:29 UTC, MikeNeilson requested changes

2024-03-29 22:29 UTC, MikeNeilson commented on docs/source/legacy-lrgs-userguide.rst
> +wishes to contribute.
Oh, `If paid support is required or desired see https://github.com/opendcs/opendcs/wiki/Getting-Paid-Support for known providers`

2024-03-29 22:29 UTC, MikeNeilson commented on docs/source/media/start/software/im-00-typical-office-high-level.JPG
I think we can change this to "Typical Setup", maybe I'm entrenched in USACE terms but it feels like we're referencing the districts there but that's a valid setup for anyone.

2024-03-29 22:29 UTC, MikeNeilson commented on docs/source/start-software.rst
> +about server set-up and how to set up an OpenHydro database can
This may need a call out that within the old docs and actual code the OpenHydro database is stilled called "OpenTSDB" or "OTSDB"

2024-03-29 22:29 UTC, MikeNeilson commented on docs/source/start-software.rst
>  the 1.8 or up to java 17 from https://adoptium.net/temurin/releases/ .
One of the tweaks I made earlier in the week made me remember the installer won't work in Java 17. OpenDCS itself will, but the installer depends on something that was removed in 17.

2024-03-29 22:29 UTC, MikeNeilson commented on docs/source/start-software.rst
>  * USERNAME: User H7
H7 is district specific.

2024-03-29 22:29 UTC, MikeNeilson commented on docs/source/start-software.rst
>  * USERNAME: User H7
`Oracle User` and `Oracle Password` are probably the best. still a bit vague but most staff would either understand that or at least be near, or have access directly to, someone who does.

2024-04-02 13:04 UTC, MikeNeilson approved these changes

2024-04-12 17:46 UTC, ktarbet approved these changes

2024-04-12 19:19 UTC, merged