Devops/add manual tests
opendcs/opendcs pull request #864
Opened 2024-12-20 19:23 UTC by MikeNeilson

## Problem Description

Fixes #473 . 

## Solution

I created a plugin that processes Gherkin Feature files and translates the data into Kiwi TCMS test cases.

Kiwi "Plans", which are groupings of test cases, are defined in the build.gradle file of the integrationtesting/manual subproject.

Tests can be assigned to more than one plan. For example, we can have a "test everything plan" and a "short smoke test" plan.

The use of Gherkin does add some complexity... I had to make an entire gradle plugin and support library to actually use it. However, it greatly simplifies structing tests which are repeated operations with minor variations - best example, see the Platform Sorting by "one of the 4 options."

I created this because I was starting to write that out manually and thus also started to go somewhat insane.

NOTE: focus is on Kiwi TCMS as HEC is self-hosting (no external access) an instance. However the plugin and processing is designed to be agnostic. It's definitely not there yet, but that's the goal. A later version of the plugin could generate CSV files, PDF form, or even a simple site (someone else is doing that work) if needed. Additionally there are other TCMS systems so we'd likely work out a way to use them.

## how you tested the change

Currently manually tested from local machine to HEC's instance.
After merge and some initial testing, I will setup a link in an action to push the tests continuously.

## Where the following done:

- [ ] Tests. Check all that apply:
   - [ ] Unit tests created or modified that run during ant test.
   - [ ] Integration tests created or modified that run during integration testing
         (Formerly called regression tests.)
   - [ ] Test procedure descriptions for manual testing
- [ ] Was relevant documentation updated?
- [ ] Were relevant config element (e.g. XML data) updated as appropriate

If you aren't sure leave unchecked and we will help guide you to want needs changing where.

2024-12-23 19:14 UTC, ktarbet requested changes
To help future developers have better context, consider having some visuals such as screen shots of kiwi in the developer documentation in a testing section.

2024-12-23 19:14 UTC, ktarbet commented on integrationtesting/manual/src/test/features/launcher/ProfileBehavior.feature
> +         When The user clicks Setup
```suggestion
         When The user clicks the Setup button
```

2024-12-23 19:14 UTC, ktarbet commented on integrationtesting/manual/src/test/features/launcher/ProfileBehavior.feature
> +         Then the Profile combo contains two entries.
```suggestion
         When The user select the default profile (in the Profile Manager), clicks copy, provides a name and closes the window
         Then The Profile combo contains two entries.
```

2024-12-27 14:51 UTC, MikeNeilson commented
> To help future developers have better context, consider having some visuals such as screen shots of kiwi in the developer documentation in a testing section.

Manually testing probably merits it's own file. Considering this is an introduction of the concept I'm quite ready to write that up yet. But definitely worth getting started.

2024-12-30 16:51 UTC, ktarbet commented on docs/source/dev-testing.rst
> +In the above `DbEdit` is an ID field with no spaces that can be referenced in a feature file, described nex
```suggestion
In the above `DbEdit` is an ID field with no spaces that can be referenced in a feature file, described next
```

2024-12-30 16:52 UTC, ktarbet commented on docs/source/dev-testing.rst
> +    As the was written it was noticed that the opening section of this configuration block is "kiwi"
```suggestion
    As this was written it was noticed that the opening section of this configuration block is "kiwi"
```

2024-12-30 16:55 UTC, ktarbet approved these changes
I've left two simple typo comments

2024-12-31 00:19 UTC, ktarbet submitted a review, later dismissed

2024-12-31 14:01 UTC, MikeNeilson commented
I'm also awaiting some feedback from @jbatterman as she's both written, and been ask to write tests.

2025-01-15 15:21 UTC, jbatterman commented on integrationtesting/manual/src/test/features/decodes/PlatformListSorting.feature
> +        When The user selects a row and clicked open
Typo: When the user selects a row and _clicks_ open

2025-01-15 15:24 UTC, jbatterman commented on integrationtesting/manual/src/test/features/decodes/PlatformListSorting.feature
> +        |platform    |
Note: Filtering by Platform seems to be broken when testing all manual Kiwi tests.  Rest of filtering works as expected.

2025-01-15 15:25 UTC, jbatterman commented on integrationtesting/manual/src/test/features/decodes/PlatformSiteSelection.feature
> +        |Select and click edit|
selecting and clicking Open

2025-01-15 15:27 UTC, jbatterman commented on integrationtesting/manual/src/test/features/decodes/SelectPlatformsForRoutingSpec.feature
> +          And The user clicks select
And The user selects a row and clicks Select

2025-01-15 15:28 UTC, jbatterman commented on integrationtesting/manual/src/test/features/decodes/SelectPlatformsForRoutingSpec.feature
> +        Given The user clicks "Select from PDT"
Select from PDT was grayed out for me, how can I test this manually?

2025-01-15 15:29 UTC, jbatterman commented on integrationtesting/manual/src/test/features/decodes/SelectPlatformsForRoutingSpec.feature
> +         Then The correct platform is added to the "Platforms Selection" List.
Then The correct platform is added to the "_Platform_ Selection" list

2025-01-15 15:30 UTC, jbatterman commented on integrationtesting/manual/src/test/features/decodes/SiteListSorting.feature
> +        Examples:
Is there a way to make this generic so any database opened will show all the options?  For instance, NWDM/NWK has acis, acis_coop, cbtt, codwr, cwms, local, nednr, nrcs, nwshb5, usbr, usgs, usgs-drgs, wyseo.

2025-01-15 15:31 UTC, jbatterman commented on integrationtesting/manual/src/test/features/decodes/SiteListSorting.feature
> +            |Select Row -> Click edit | local       |
|selects a row and clicks Open|

2025-01-15 15:31 UTC, jbatterman commented on integrationtesting/manual/src/test/features/decodes/SiteListSorting.feature
> +            |Double Click Row         | local       |
|double-clicks a row|

2025-01-15 15:31 UTC, jbatterman commented on integrationtesting/manual/src/test/features/decodes/SiteListSorting.feature
> +            |Select Row -> Click edit | description |
|selects a row and clicks Open|

2025-01-15 15:31 UTC, jbatterman commented on integrationtesting/manual/src/test/features/decodes/SiteListSorting.feature
> +            |Double Click Row         | description |
|double-clicks a row|

2025-01-15 15:33 UTC, jbatterman commented on integrationtesting/manual/src/test/features/decodes/SitePropertyListSorting.feature
> +         Then The correct tooltip is shown. NOTE: you may have to determine this by context.
No tooltips are available in my manual testing

2025-01-15 15:34 UTC, jbatterman commented on integrationtesting/manual/src/test/features/decodes/SitePropertyListSorting.feature
> +        Given A database with sites is available that have more than one extra property. Create additional properties on a site if necessary.
Note: When creating a new property to run this manual test, the new property row doesn't appear until after a Commit, close, and reopen is done on the Site.

2025-01-15 15:36 UTC, jbatterman commented on integrationtesting/manual/src/test/features/launcher/ProfileBehavior.feature
> +         When The User starts the launcher
Do we need to define the two ways to do this?  launcher_start.bat or dcstool_start.bat

2025-01-15 15:41 UTC, jbatterman commented on integrationtesting/manual/src/test/features/decodes/PlatformListSorting.feature
> +
These TCs show up a little weird in Kiwi.  See TC-1286, 1287, 1288, 1289.
They read a little confusing - 

Given: A database with many platforms available.
Given: The user filters the platform list by platform selection
When: The user double clicks a row
Then: The correct platform is opened
Given: The user filters the platform list by platform
When: The user selects a row and clicks open.
Then: The correct platform is opened

Here in the Kiwi test - I think these are supposed to be two separate tests but get merged together.  At least I think they'd be more understandable if they were two separate tests.

2025-01-15 15:43 UTC, jbatterman commented
I added my comments to the tests currently in this pull request.  If you'd like me to work on adding additional tests I'll need a walkthrough from @MikeNeilson or @ktarbet on how to do that.  A couple of my comments are potential issues in the GUI that need to be opened - let me know if you'd like me to do that.

2025-02-06 14:36 UTC, MikeNeilson commented on integrationtesting/manual/src/test/features/decodes/SelectPlatformsForRoutingSpec.feature
> +        Given The user clicks "Select from PDT"
I'll have to investigate, probably a setting in user.properties to retrieve the info but that would need to be called out in the test.

2025-02-06 14:37 UTC, MikeNeilson commented on integrationtesting/manual/src/test/features/decodes/SiteListSorting.feature
> +        Examples:
Not in a meaningful way I can think of. There's also some consideration of not even having those columns but including the information and way to sort it in a different way.

2025-02-06 14:39 UTC, MikeNeilson commented on integrationtesting/manual/src/test/features/decodes/SitePropertyListSorting.feature
> +         Then The correct tooltip is shown. NOTE: you may have to determine this by context.
Hmm, at least several should. I'll run through it later.

2025-02-06 14:40 UTC, MikeNeilson commented on integrationtesting/manual/src/test/features/decodes/SitePropertyListSorting.feature
> +        Given A database with sites is available that have more than one extra property. Create additional properties on a site if necessary.
Odd. and something to open a separate issue for.

2025-02-06 14:42 UTC, MikeNeilson commented on integrationtesting/manual/src/test/features/launcher/ProfileBehavior.feature
> +         When The User starts the launcher
Maybe, but for now I don't think so. it's the same script with a different filename.

2025-02-06 14:56 UTC, MikeNeilson commented on integrationtesting/manual/src/test/features/decodes/PlatformListSorting.feature
> +
Wait, no I think I did that intentionally. Though it may have been the wrong thing to do. Here's my thought process:

1. Both are related specifically to filtering
2. You wouldn't be opening the application again.

Perhaps the flaw is the wording of the 2nd given. Either it shouldn't exist or it should be more explicit to just go back to the list and do the other operation instead.

2025-02-10 22:37 UTC, ktarbet approved these changes

2025-03-03 21:38 UTC, ktarbet approved these changes

2025-03-03 21:49 UTC, merged